import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/common/header";
import Footer from "@/components/common/footer";
import FilterButtonProvider from "@/context/filterbtn";

const myFont = localFont({
  src: [
    {
      path: "../../public/font/Co Headline Light.woff",
      style: "light",
    },
    {
      path: "../../public/font/Co-Headline-Bold.woff",
      style: "bold",
    },
    {
      path: "../../public/font/Co Headline.woff",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${myFont.className} antialiased`}>
        <Header />
        <FilterButtonProvider>{children}</FilterButtonProvider>
        <Footer />
      </body>
    </html>
  );
}
